// === node-emitter.js ===
/**
 * @module node-emitter
 * @description Converts pipeline AST to Node 20 (ESM) using playwright + axios.
 * @dependencies logger
 */

import { logger } from "../utils/logger.js";
import { isValidRegex } from "../utils/value-transforms.js";
const MODULE = "node-emitter";

export function emitNode(pipeline) {
  logger.info(MODULE, "emit-start", { name: pipeline.name });
  const lines = [
    "// Generated by FlowScrape v3",
    `// Pipeline: ${pipeline.name ?? "Untitled"}`,
    `// Generated: ${new Date().toISOString()}`,
    "import { chromium } from 'playwright';",
    "import fs from 'fs';",
    "import path from 'path';",
    "",
    `const TARGET_ORIGIN = '${pipeline.targetOrigin ?? ""}';`,
    `const MIN_DELAY_MS  = 800;`,
    "",
    `const PROXY = process.env.FS_PROXY_HOST ? {`,
    `  server:   process.env.FS_PROXY_HOST,`,
    `  username: process.env.FS_PROXY_USER ?? '',`,
    `  password: process.env.FS_PROXY_PASS ?? '',`,
    `} : undefined;`,
    "",
    `// Credentials are not written into this script. Each one appears as`,
    `// __FS_ENV__NAME__ and is read from the environment variable NAME at run`,
    `// time; a name that is not set resolves to an empty string.`,
    `const fsEnv = s => typeof s === 'string'`,
    `  ? s.replace(/__FS_ENV__([A-Z0-9_]+)__/g, (_, n) => process.env[n] ?? '')`,
    `  : s;`,
    "",
    `// Value transforms, mirroring utils/value-transforms.js. The pipeline`,
    `// cleans values as it extracts them; a script that skipped this would run,`,
    `// produce a file, and fill the number columns with currency symbols.`,
    `const fsNumber = t => {`,
    `  const m = String(t ?? '').match(/-?\\d[\\d.,\\s]*\\d|-?\\d/);`,
    `  if (!m) return null;`,
    `  let b = m[0].replace(/\\s/g, '');`,
    `  const c = b.lastIndexOf(','), d = b.lastIndexOf('.');`,
    `  if (c > -1 && d > -1) {`,
    `    const dec = c > d ? ',' : '.', th = dec === ',' ? '.' : ',';`,
    `    b = b.split(th).join('').replace(dec, '.');`,
    `  } else if (c > -1) {`,
    `    const after = b.length - c - 1, single = b.indexOf(',') === c;`,
    `    b = single && after > 0 && after <= 2 ? b.replace(',', '.') : b.split(',').join('');`,
    `  } else if (d > -1) {`,
    `    const after = b.length - d - 1, single = b.indexOf('.') === d;`,
    `    if (!(single && after > 0 && after <= 2)) b = b.split('.').join('');`,
    `  }`,
    `  const n = Number(b);`,
    `  return Number.isFinite(n) ? n : null;`,
    `};`,
    `const fsUrl = (v, base) => { try { return new URL(String(v ?? '').trim(), base).href; } catch { return v; } };`,
    `const fsRegex = (v, p) => { const m = String(v ?? '').match(new RegExp(p)); return m ? (m[1] ?? m[0]) : null; };`,
    `const fsTrim = v => String(v ?? '').replace(/\\s+/g, ' ').trim();`,
    "",
    `// What an IF_ELSE branch reads before it decides. null means "no such`,
    `// element", which every condition treats as not-matching rather than as`,
    `// an empty string — the two are different, and conflating them puts every`,
    `// missing row into the wrong branch.`,
    `const fsText = async loc => (await loc.count()) > 0 ? fsTrim(await loc.first().innerText()) : null;`,
    `const fsAttr = async (loc, a) => (await loc.count()) > 0 ? await loc.first().getAttribute(a) : null;`,
    "",
    `const sleep = ms => new Promise(r => setTimeout(r, ms));`,
    `const jitter = (min, max) => min + Math.random() * (max - min);`,
    "",
    `(async () => {`,
    `  const browser = await chromium.launch({ proxy: PROXY });`,
    `  const context = await browser.newContext();`,
    `  const page    = await context.newPage();`,
    `  try {`,
  ];

  for (const step of pipeline.steps ?? []) {
    lines.push(..._emitNodeStep(step).map((l) => "    " + l));
  }

  lines.push(`  } finally {`, `    await browser.close();`, `  }`, `})();`, "");
  return lines.join("\n");
}

/**
 * One IF_ELSE condition as a JavaScript expression over `_loc`.
 *
 * Mirrors utils/conditions.js, which is where the extension's copy lives; the
 * pair is held together by a test that emits every condition in the registry
 * and fails on any that comes back stubbed.
 *
 * @returns {string|null} null when the condition cannot be expressed
 */
function _conditionNode(condition, config, esc) {
  const value = esc(String(config.value ?? ""));
  const attr = esc(String(config.attr ?? ""));
  const num = Number(String(config.value ?? "").trim());
  const numeric = (op) =>
    Number.isFinite(num)
      ? `((n => n !== null && n ${op} ${num})(fsNumber(await fsText(_loc))))`
      : null;

  switch (condition) {
    case "exists":
      return `(await _loc.count()) > 0`;
    case "not-exists":
      return `(await _loc.count()) === 0`;
    case "is-empty":
      return `((t => t === null || t === '')(await fsText(_loc)))`;
    case "not-empty":
      return `((t => t !== null && t !== '')(await fsText(_loc)))`;
    case "text-equals":
      return `(await fsText(_loc)) === fsTrim('${value}')`;
    case "text-contains":
      return `((t => t !== null && t.includes(fsTrim('${value}')))(await fsText(_loc)))`;
    case "text-matches":
      if (!isValidRegex(config.value ?? "")) return null;
      return `((t => t !== null && new RegExp('${value.replace(/\\/g, "\\\\")}').test(t))(await fsText(_loc)))`;
    case "attr-equals":
      return `((a => a !== null && a.trim() === '${value}'.trim())(await fsAttr(_loc, '${attr}')))`;
    case "attr-contains":
      return `((a => a !== null && a.includes('${value}'))(await fsAttr(_loc, '${attr}')))`;
    case "attr-exists":
      return `(await fsAttr(_loc, '${attr}')) !== null`;
    case "number-equals":
      return numeric("===");
    case "number-gt":
      return numeric(">");
    case "number-lt":
      return numeric("<");
    default:
      return null;
  }
}

function _emitNodeStep(step) {
  const { type, config = {} } = step;
  const esc = (s) => String(s ?? "").replace(/'/g, "\\'");
  switch (type) {
    case "WEBSITE":
    case "NAVIGATE":
      return [
        `await page.goto('${esc(config.url ?? "")}');`,
        `await page.waitForLoadState('networkidle');`,
        "",
      ];
    case "API":
      return _apiNode(config);
    case "CLICK":
      return [`await page.click('${esc(config.selector ?? "")}');`, ""];
    case "WAIT": {
      const timeout = Number(config.timeout) || 15000;
      if (config.mode === "selector-visible") {
        return [
          `await page.waitForSelector('${esc(config.selector ?? "")}', { state: 'visible', timeout: ${timeout} });`,
          "",
        ];
      }
      if (config.mode === "selector-gone") {
        return [
          `await page.waitForSelector('${esc(config.selector ?? "")}', { state: 'hidden', timeout: ${timeout} });`,
          "",
        ];
      }
      if (config.mode === "DOM-stable") {
        // Playwright has no "the DOM stopped changing"; network idle is the
        // closest thing it offers, and is what the mode is used for in
        // practice — waiting out a search or a filter.
        return [
          `await page.waitForLoadState('networkidle', { timeout: ${timeout} });`,
          "",
        ];
      }
      return [`await sleep(${config.ms ?? 1000});`, ""];
    }
    case "EXTRACT":
      return _extractNode(config);
    case "FORM_FILL":
      return _formFillNode(config);
    case "EXPORT":
      return [
        `// EXPORT → ${config.format ?? "csv"} (implement write here)`,
        "",
      ];
    case "SCROLL": {
      // config.amount is what the UI writes; `value` was read here, so every
      // exported scroll used the hardcoded default.
      const amount = config.amount ?? config.value ?? 300;
      if (config.mode === "selector" && config.selector) {
        return [
          `await page.locator('${esc(config.selector)}').scrollIntoViewIfNeeded();`,
          "",
        ];
      }
      if (config.mode === "percent") {
        return [
          `await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight * ${Number(amount) / 100}));`,
          `await sleep(500);`,
          "",
        ];
      }
      if (config.mode === "infinite" || config.mode === "bottom") {
        const maxScrolls = Number(config.maxScrolls) || 50;
        const settle = Number(config.settleMs) || 1200;
        return [
          `// Scroll until the page stops growing, or ${maxScrolls} scrolls.`,
          `let _lastHeight = 0;`,
          `for (let i = 0; i < ${maxScrolls}; i++) {`,
          `  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));`,
          `  await sleep(${settle});`,
          `  const _h = await page.evaluate(() => document.documentElement.scrollHeight);`,
          `  if (_h === _lastHeight) break;`,
          `  _lastHeight = _h;`,
          `}`,
          "",
        ];
      }
      return [
        `await page.evaluate(() => window.scrollBy(0, ${amount}));`,
        `await sleep(500);`,
        "",
      ];
    }
    case "LOOP": {
      const lines = [
        `// LOOP: ${config.type || "count"} (max: ${config.max ?? 10})`,
      ];
      if (config.type === "elements" && config.selector) {
        lines.push(
          `const elements = await page.locator('${esc(config.selector)}').all();`,
        );
        lines.push(
          `for (let i = 0; i < Math.min(elements.length, ${config.max ?? 10}); i++) {`,
        );
        lines.push(`  const el = elements[i];`);
      } else {
        lines.push(`for (let i = 0; i < ${config.max ?? 10}; i++) {`);
      }
      if (config.type === "paginate" && config.selector) {
        // The emitted loop used to ignore paginate mode entirely: it ran the
        // body N times without ever clicking Next, so an exported script
        // scraped page one N times over.
        lines.push(
          `  if (i > 0) {`,
          `    const _next = page.locator('${esc(config.selector)}').first();`,
          `    if ((await _next.count()) === 0 || !(await _next.isEnabled())) {`,
          `      console.log(\`Pagination: stopped after \${i} page(s).\`);`,
          `      break;`,
          `    }`,
          `    await _next.click();`,
          `    await page.waitForLoadState('networkidle');`,
          `  }`,
        );
      }
      for (const child of step.children ?? []) {
        lines.push(..._emitNodeStep(child).map((l) => "  " + l));
      }
      lines.push(`}`, "");
      return lines;
    }
    case "IF_ELSE": {
      const condition = config.condition || "exists";
      const lines = [
        `// IF_ELSE: ${condition} - ${esc(config.selector ?? "")}`,
      ];
      const test = _conditionNode(condition, config, esc);
      if (test === null) {
        // Emitted as a refusal rather than as `if (true)`, which is what this
        // used to do for every condition but `exists`: the script ran, produced
        // a file, and had silently ignored its own branching.
        lines.push(
          `// UNSUPPORTED: condition '${condition}' cannot be expressed here.`,
          `throw new Error("FlowScrape: IF_ELSE condition '${condition}' is not exportable");`,
          "",
        );
        return lines;
      }
      // Braced: two sibling branches in the same scope would otherwise both
      // declare `_loc`, and the script would not parse. Caught by the check
      // that compiles the emitted output rather than pattern-matching it.
      lines.push(
        `{`,
        `  const _loc = page.locator('${esc(config.selector ?? "")}');`,
        `  if (${test}) {`,
      );
      for (const child of step.ifBranch ?? []) {
        lines.push(..._emitNodeStep(child).map((l) => "    " + l));
      }
      lines.push(`  } else {`);
      for (const child of step.elseBranch ?? []) {
        lines.push(..._emitNodeStep(child).map((l) => "    " + l));
      }
      lines.push(`  }`, `}`, "");
      return lines;
    }
    case "FILL":
    case "TYPE":
      return _emitNodeFill(config, esc);

    case "HOVER":
      return [`await page.hover('${esc(config.selector)}');`, ""];

    case "SELECT":
      return [
        `await page.selectOption('${esc(config.selector)}', '${esc(config.value)}');`,
        "",
      ];

    case "KEYBOARD":
      return [
        `await page.keyboard.press('${esc(_playwrightKey(config.key))}');`,
        "",
      ];

    case "SCREENSHOT":
      return [
        `await page.screenshot({ path: \`screenshot_\${Date.now()}.png\` });`,
        "",
      ];

    case "PAGE_DATA": {
      // JSON-LD and the page's meta tags carry over cleanly. The microdata
      // reader does not: it is a hundred lines of DOM walking in
      // content/page-data.js, and a second, compact implementation here would
      // drift from it. So the script reads what it can and says loudly when it
      // finds nothing — the pipeline would have fallen back to microdata there,
      // and a silent difference is exactly what the audit was about.
      const wantType = esc(config.type ?? "");
      const flat = config.flatten !== false;
      return [
        `{`,
        `  const pageData = await page.evaluate(() => {`,
        `    const abs = v => { try { return new URL(String(v ?? '').trim(), location.href).href; } catch { return v; } };`,
        `    const records = [];`,
        `    const walk = (d, depth = 0) => {`,
        `      if (!d || depth > 6) return;`,
        `      if (Array.isArray(d)) return d.forEach(x => walk(x, depth + 1));`,
        `      if (typeof d !== 'object') return;`,
        `      if (Array.isArray(d['@graph'])) {`,
        `        d['@graph'].forEach(x => walk(x, depth + 1));`,
        `        if (Object.keys(d).filter(k => k !== '@graph' && k !== '@context').length === 0) return;`,
        `      }`,
        `      records.push(d);`,
        `    };`,
        `    for (const el of document.querySelectorAll('script[type="application/ld+json"]')) {`,
        `      try { walk(JSON.parse(el.textContent || '')); } catch {}`,
        `    }`,
        `    const meta = {};`,
        `    for (const el of document.querySelectorAll('meta[content]')) {`,
        `      const k = el.getAttribute('property') || el.getAttribute('name');`,
        `      if (!k) continue;`,
        `      if (!/^(og|twitter|product|article|book|music|video|profile):/.test(k) &&`,
        `          !['description','keywords','author','robots'].includes(k)) continue;`,
        `      const v = el.getAttribute('content');`,
        `      meta[k] = /(?:^|:)(?:url|image|video|audio|player)$/.test(k) ? abs(v) : String(v ?? '').replace(/\\s+/g, ' ').trim();`,
        `    }`,
        `    return { records, meta, url: location.href, title: document.title };`,
        `  });`,
        ...(wantType
          ? [
              `  pageData.records = pageData.records.filter(r => {`,
              `    const t = Array.isArray(r['@type']) ? r['@type'] : [r['@type']];`,
              `    return t.some(x => String(x ?? '').toLowerCase() === '${wantType.toLowerCase()}');`,
              `  });`,
            ]
          : []),
        `  if (pageData.records.length === 0) {`,
        `    console.warn('PAGE_DATA: no JSON-LD found. The extension would also try microdata here;');`,
        `    console.warn('           this script does not carry that reader, so the result may differ.');`,
        `  }`,
        ...(flat
          ? [
              `  const flat = (v, p = '', out = {}, depth = 0, seen = new Set()) => {`,
              `    if (v == null) return out;`,
              `    if (Array.isArray(v)) {`,
              `      if (v.every(x => x === null || typeof x !== 'object')) out[p || 'value'] = v.join(', ');`,
              `      else v.forEach((x, i) => flat(x, p ? p + '.' + i : String(i), out, depth + 1, seen));`,
              `      return out;`,
              `    }`,
              `    if (typeof v === 'object') {`,
              `      if (depth >= 6 || seen.has(v)) return out;`,
              `      seen.add(v);`,
              `      for (const [k, val] of Object.entries(v)) flat(val, p ? p + '.' + k : k, out, depth + 1, seen);`,
              `      seen.delete(v);`,
              `      return out;`,
              `    }`,
              `    out[p || 'value'] = v;`,
              `    return out;`,
              `  };`,
              `  pageData.records = pageData.records.map(r => flat(r));`,
            ]
          : []),
        `  for (const record of pageData.records) console.log(JSON.stringify(record));`,
        `}`,
        "",
      ];
    }

    case "PAGINATE": {
      // A bare click was what this emitted. Past the last page it clicks
      // nothing and reports success — the same defect the extension's PAGINATE
      // step had. `break` is not emitted here because a top-level PAGINATE has
      // no loop to break out of; a paginating LOOP emits its own (see below).
      const sel = esc(config.selector ?? "");
      return [
        `{`,
        `  const _next = page.locator('${sel}').first();`,
        `  if ((await _next.count()) > 0 && (await _next.isEnabled())) {`,
        `    await _next.click();`,
        `    await page.waitForLoadState('networkidle');`,
        `  } else {`,
        `    console.log('Pagination: no further pages.');`,
        `  }`,
        `}`,
        "",
      ];
    }

    case "DRAG_DROP":
      return [
        `await page.dragAndDrop('${esc(config.source)}', '${esc(config.target)}');`,
        "",
      ];

    default:
      // Not silently dropped: emitUnsupported collects these and the caller
      // reports them, so an exported script cannot quietly do less than the
      // pipeline it came from.
      return [
        `// UNSUPPORTED: '${type}' has no equivalent in a standalone script.`,
        `throw new Error('FlowScrape step ${type} is not exportable');`,
        "",
      ];
  }
}

/** Playwright key names differ slightly from the panel's combo strings. */
function _playwrightKey(key) {
  return String(key ?? "Enter")
    .split("+")
    .map((part) => (part === "Ctrl" ? "Control" : part))
    .join("+");
}

function _emitNodeFill(config, esc) {
  const lines = [];
  const fields =
    config.mode === "multi" &&
    Array.isArray(config.fields) &&
    config.fields.length
      ? config.fields
      : [{ selector: config.selector, value: config.text }];

  for (const field of fields) {
    if (!field?.selector) continue;
    lines.push(
      `await page.fill('${esc(field.selector)}', fsEnv('${esc(field.value ?? "")}'));`,
    );
  }
  if (config.submitSelector) {
    lines.push(`await page.click('${esc(config.submitSelector)}');`);
    lines.push(`await page.waitForLoadState('networkidle');`);
  }
  lines.push("");
  return lines;
}

/**
 * Wrap a read in the transforms the field carries, innermost first.
 * @returns {string|null} null when a transform cannot be emitted faithfully
 */
function _transformNode(expr, field) {
  let out = expr;
  for (const name of field.transform ?? []) {
    if (name === "number") out = `fsNumber(${out})`;
    else if (name === "trim") out = `fsTrim(${out})`;
    else if (name === "url") out = `fsUrl(${out}, page.url())`;
    else if (name === "lower") out = `String(${out} ?? '').toLowerCase()`;
    else if (name === "upper") out = `String(${out} ?? '').toUpperCase()`;
    else if (name === "regex") {
      const raw = String(field.regexPattern ?? "");
      if (!isValidRegex(raw)) return null; // the caller emits a refusal
      // A regex is full of backslashes, and the quote-escaper alone turned
      // `\\S` into a bare `S` inside the emitted literal, so the pattern
      // silently matched nothing. Backslashes first, then quotes.
      const pattern = raw.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
      out = `fsRegex(${out}, '${pattern}')`;
    }
  }
  return out;
}

function _extractNode(config) {
  const lines = ["const extracted = {};"];
  for (const field of config.fields ?? []) {
    const { name, selector, attribute } = field;
    const read = attribute
      ? `await page.getAttribute('${selector}', '${attribute}')`
      : `await page.innerText('${selector}')`;
    const expr = _transformNode(read, field);
    if (expr === null) {
      lines.push(
        `// INVALID: field '${name}' has a pattern JavaScript will not accept.`,
        `throw new Error("FlowScrape field '${name}': invalid regex pattern");`,
      );
      continue;
    }
    lines.push(`extracted['${name}'] = ${expr};`);
  }
  lines.push(`console.log(JSON.stringify(extracted));`, "");
  return lines;
}

function _formFillNode(config) {
  const lines = [
    `const rows = csv.parse(fs.readFileSync(process.env.FS_DATA_FILE ?? 'data.csv'), { columns: true });`,
    `for (const row of rows) {`,
  ];
  for (const m of config.fieldMappings ?? []) {
    lines.push(
      `  await page.fill('${m.selector ?? ""}', row['${m.column ?? ""}'] ?? '');`,
    );
  }
  if (config.submitSelector)
    lines.push(`  await page.click('${config.submitSelector}');`);
  lines.push(
    `  await sleep(jitter(${config.interRowDelay?.min ?? 1200}, ${config.interRowDelay?.max ?? 3000}));`,
  );
  lines.push(`}`, "");
  return lines;
}

function _apiNode(config) {
  const esc = (s) => String(s ?? "").replace(/'/g, "\\'");
  const method = String(config.method ?? "GET").toUpperCase();
  const headers = config.headers ?? '{"Accept":"application/json"}';
  const body = config.body ?? "";
  const timeout = Number(config.timeoutMs ?? 15000);
  const failOnHttp = config.failOnHttpError !== false;

  return [
    `const apiController = new AbortController();`,
    `const apiTimer = setTimeout(() => apiController.abort(), ${timeout});`,
    `let apiHeaders = {};`,
    `try { apiHeaders = JSON.parse(fsEnv('${esc(headers)}')); } catch { apiHeaders = {}; }`,
    `const apiResp = await fetch('${esc(config.url ?? "")}', {`,
    `  method: '${esc(method)}',`,
    `  headers: apiHeaders,`,
    `  body: '${esc(body)}' ? fsEnv('${esc(body)}') : undefined,`,
    `  signal: apiController.signal,`,
    `});`,
    `clearTimeout(apiTimer);`,
    failOnHttp
      ? `if (!apiResp.ok) throw new Error('API failed: ' + apiResp.status + ' ' + apiResp.statusText);`
      : `// failOnHttpError disabled`,
    `const apiText = await apiResp.text();`,
    `let apiBody = apiText;`,
    `try { apiBody = JSON.parse(apiText); } catch {}`,
    `const apiResult = { status: apiResp.status, ok: apiResp.ok, body: apiBody };`,
    `console.log('API_RESULT', JSON.stringify(apiResult));`,
    "",
  ];
}

// === END node-emitter.js ===
