// === node-emitter.js ===
/**
 * @module node-emitter
 * @description Converts pipeline AST to Node 20 (ESM) using playwright + axios.
 * @dependencies logger
 */

import { logger } from '../utils/logger.js';
const MODULE = 'node-emitter';

export function emitNode(pipeline) {
  logger.info(MODULE, 'emit-start', { name: pipeline.name });
  const lines = [
    '// Generated by FlowScrape v3',
    `// Pipeline: ${pipeline.name ?? 'Untitled'}`,
    `// Generated: ${new Date().toISOString()}`,
    "import { chromium } from 'playwright';",
    "import fs from 'fs';",
    "import path from 'path';",
    "import csv from 'csv-parse/sync';",
    '',
    `const TARGET_ORIGIN = '${pipeline.targetOrigin ?? ''}';`,
    `const MIN_DELAY_MS  = 800;`,
    '',
    `const PROXY = process.env.FS_PROXY_HOST ? {`,
    `  server:   process.env.FS_PROXY_HOST,`,
    `  username: process.env.FS_PROXY_USER ?? '',`,
    `  password: process.env.FS_PROXY_PASS ?? '',`,
    `} : undefined;`,
    '',
    `const sleep = ms => new Promise(r => setTimeout(r, ms));`,
    `const jitter = (min, max) => min + Math.random() * (max - min);`,
    '',
    `(async () => {`,
    `  const browser = await chromium.launch({ proxy: PROXY });`,
    `  const context = await browser.newContext();`,
    `  const page    = await context.newPage();`,
    `  try {`,
  ];

  for (const step of (pipeline.steps ?? [])) {
    lines.push(..._emitNodeStep(step).map(l => '    ' + l));
  }

  lines.push(
    `  } finally {`,
    `    await browser.close();`,
    `  }`,
    `})();`,
    '',
  );
  return lines.join('\n');
}

function _emitNodeStep(step) {
  const { type, config = {} } = step;
  const esc = s => String(s ?? '').replace(/'/g, "\\'");
  switch (type) {
    case 'NAVIGATE':
      return [`await page.goto('${esc(config.url ?? '')}');`, `await page.waitForLoadState('networkidle');`, ''];
    case 'CLICK':
      return [`await page.click('${esc(config.selector ?? '')}');`, ''];
    case 'WAIT':
      if (config.mode === 'selector-visible') return [`await page.waitForSelector('${esc(config.selector ?? '')}');`, ''];
      return [`await sleep(${config.ms ?? 1000});`, ''];
    case 'EXTRACT':
      return _extractNode(config);
    case 'FORM_FILL':
      return _formFillNode(config);
    case 'EXPORT':
      return [`// EXPORT → ${config.format ?? 'csv'} (implement write here)`, ''];
    case 'SCROLL':
      return [`await page.evaluate(() => window.scrollBy(0, ${config.value ?? 300}));`, ''];
    default:
      return [`// TODO: ${type}`, ''];
  }
}

function _extractNode(config) {
  const lines = ['const extracted = {};'];
  for (const { name, selector, attribute } of (config.fields ?? [])) {
    if (attribute) {
      lines.push(`extracted['${name}'] = await page.getAttribute('${selector}', '${attribute}');`);
    } else {
      lines.push(`extracted['${name}'] = await page.innerText('${selector}');`);
    }
  }
  lines.push(`console.log(JSON.stringify(extracted));`, '');
  return lines;
}

function _formFillNode(config) {
  const lines = [
    `const rows = csv.parse(fs.readFileSync(process.env.FS_DATA_FILE ?? 'data.csv'), { columns: true });`,
    `for (const row of rows) {`,
  ];
  for (const m of (config.fieldMappings ?? [])) {
    lines.push(`  await page.fill('${m.selector ?? ''}', row['${m.column ?? ''}'] ?? '');`);
  }
  if (config.submitSelector) lines.push(`  await page.click('${config.submitSelector}');`);
  lines.push(`  await sleep(jitter(${config.interRowDelay?.min ?? 1200}, ${config.interRowDelay?.max ?? 3000}));`);
  lines.push(`}`, '');
  return lines;
}

// === END node-emitter.js ===
