// === node-emitter.js ===
/**
 * @module node-emitter
 * @description Converts pipeline AST to Node 20 (ESM) using playwright + axios.
 * @dependencies logger
 */

import { logger } from "../utils/logger.js";
const MODULE = "node-emitter";

export function emitNode(pipeline) {
  logger.info(MODULE, "emit-start", { name: pipeline.name });
  const lines = [
    "// Generated by FlowScrape v3",
    `// Pipeline: ${pipeline.name ?? "Untitled"}`,
    `// Generated: ${new Date().toISOString()}`,
    "import { chromium } from 'playwright';",
    "import fs from 'fs';",
    "import path from 'path';",
    "import csv from 'csv-parse/sync';",
    "",
    `const TARGET_ORIGIN = '${pipeline.targetOrigin ?? ""}';`,
    `const MIN_DELAY_MS  = 800;`,
    "",
    `const PROXY = process.env.FS_PROXY_HOST ? {`,
    `  server:   process.env.FS_PROXY_HOST,`,
    `  username: process.env.FS_PROXY_USER ?? '',`,
    `  password: process.env.FS_PROXY_PASS ?? '',`,
    `} : undefined;`,
    "",
    `const sleep = ms => new Promise(r => setTimeout(r, ms));`,
    `const jitter = (min, max) => min + Math.random() * (max - min);`,
    "",
    `(async () => {`,
    `  const browser = await chromium.launch({ proxy: PROXY });`,
    `  const context = await browser.newContext();`,
    `  const page    = await context.newPage();`,
    `  try {`,
  ];

  for (const step of pipeline.steps ?? []) {
    lines.push(..._emitNodeStep(step).map((l) => "    " + l));
  }

  lines.push(`  } finally {`, `    await browser.close();`, `  }`, `})();`, "");
  return lines.join("\n");
}

function _emitNodeStep(step) {
  const { type, config = {} } = step;
  const esc = (s) => String(s ?? "").replace(/'/g, "\\'");
  switch (type) {
    case "WEBSITE":
    case "NAVIGATE":
      return [
        `await page.goto('${esc(config.url ?? "")}');`,
        `await page.waitForLoadState('networkidle');`,
        "",
      ];
    case "API":
      return _apiNode(config);
    case "CLICK":
      return [`await page.click('${esc(config.selector ?? "")}');`, ""];
    case "WAIT":
      if (config.mode === "selector-visible")
        return [
          `await page.waitForSelector('${esc(config.selector ?? "")}');`,
          "",
        ];
      return [`await sleep(${config.ms ?? 1000});`, ""];
    case "EXTRACT":
      return _extractNode(config);
    case "FORM_FILL":
      return _formFillNode(config);
    case "EXPORT":
      return [
        `// EXPORT → ${config.format ?? "csv"} (implement write here)`,
        "",
      ];
    case "SCROLL":
      return [
        `await page.evaluate(() => window.scrollBy(0, ${config.value ?? 300}));`,
        "",
      ];
    case "LOOP": {
      const lines = [
        `// LOOP: ${config.type || 'count'} (max: ${config.max ?? 10})`,
      ];
      if (config.type === 'elements' && config.selector) {
        lines.push(`const elements = await page.locator('${esc(config.selector)}').all();`);
        lines.push(`for (let i = 0; i < Math.min(elements.length, ${config.max ?? 10}); i++) {`);
        lines.push(`  const el = elements[i];`);
      } else {
        lines.push(`for (let i = 0; i < ${config.max ?? 10}; i++) {`);
      }
      for (const child of step.children ?? []) {
        lines.push(..._emitNodeStep(child).map(l => "  " + l));
      }
      lines.push(`}`, "");
      return lines;
    }
    case "IF_ELSE": {
      const condition = config.condition || 'exists';
      const lines = [
        `// IF_ELSE: ${condition} - ${esc(config.selector ?? '')}`,
      ];
      if (condition === 'exists') {
        lines.push(`if (await page.locator('${esc(config.selector ?? '')}').count() > 0) {`);
      } else {
        lines.push(`if (true) { // TODO: impl extended condition ${condition}`);
      }
      for (const child of step.ifBranch ?? []) {
        lines.push(..._emitNodeStep(child).map(l => "  " + l));
      }
      lines.push(`} else {`);
      for (const child of step.elseBranch ?? []) {
        lines.push(..._emitNodeStep(child).map(l => "  " + l));
      }
      lines.push(`}`, "");
      return lines;
    }
    default:
      return [`// TODO: ${type}`, ""];
  }
}

function _extractNode(config) {
  const lines = ["const extracted = {};"];
  for (const { name, selector, attribute } of config.fields ?? []) {
    if (attribute) {
      lines.push(
        `extracted['${name}'] = await page.getAttribute('${selector}', '${attribute}');`,
      );
    } else {
      lines.push(`extracted['${name}'] = await page.innerText('${selector}');`);
    }
  }
  lines.push(`console.log(JSON.stringify(extracted));`, "");
  return lines;
}

function _formFillNode(config) {
  const lines = [
    `const rows = csv.parse(fs.readFileSync(process.env.FS_DATA_FILE ?? 'data.csv'), { columns: true });`,
    `for (const row of rows) {`,
  ];
  for (const m of config.fieldMappings ?? []) {
    lines.push(
      `  await page.fill('${m.selector ?? ""}', row['${m.column ?? ""}'] ?? '');`,
    );
  }
  if (config.submitSelector)
    lines.push(`  await page.click('${config.submitSelector}');`);
  lines.push(
    `  await sleep(jitter(${config.interRowDelay?.min ?? 1200}, ${config.interRowDelay?.max ?? 3000}));`,
  );
  lines.push(`}`, "");
  return lines;
}

function _apiNode(config) {
  const esc = (s) => String(s ?? "").replace(/'/g, "\\'");
  const method = String(config.method ?? "GET").toUpperCase();
  const headers = config.headers ?? '{"Accept":"application/json"}';
  const body = config.body ?? "";
  const timeout = Number(config.timeoutMs ?? 15000);
  const failOnHttp = config.failOnHttpError !== false;

  return [
    `const apiController = new AbortController();`,
    `const apiTimer = setTimeout(() => apiController.abort(), ${timeout});`,
    `let apiHeaders = {};`,
    `try { apiHeaders = JSON.parse('${esc(headers)}'); } catch { apiHeaders = {}; }`,
    `const apiResp = await fetch('${esc(config.url ?? "")}', {`,
    `  method: '${esc(method)}',`,
    `  headers: apiHeaders,`,
    `  body: '${esc(body)}' ? '${esc(body)}' : undefined,`,
    `  signal: apiController.signal,`,
    `});`,
    `clearTimeout(apiTimer);`,
    failOnHttp
      ? `if (!apiResp.ok) throw new Error('API failed: ' + apiResp.status + ' ' + apiResp.statusText);`
      : `// failOnHttpError disabled`,
    `const apiText = await apiResp.text();`,
    `let apiBody = apiText;`,
    `try { apiBody = JSON.parse(apiText); } catch {}`,
    `const apiResult = { status: apiResp.status, ok: apiResp.ok, body: apiBody };`,
    `console.log('API_RESULT', JSON.stringify(apiResult));`,
    "",
  ];
}

// === END node-emitter.js ===
