// === python-emitter.js ===
/**
 * @module python-emitter
 * @description Converts a pipeline JSON AST to Python 3.11 script
 *   using playwright (browser automation) + requests (HTTP).
 *   Credentials detected by pipeline-compiler.js are replaced with __FS_ENV__NAME__
 *   markers and resolved from the environment at run time by fs_env().
 *
 *   Design decision: We emit Python rather than Playwright-specific code because
 *   Python is the most common scripting language for automation. The output is
 *   self-contained: user runs `pip install playwright requests && playwright install`.
 *
 * @dependencies logger
 */

import { logger } from "../utils/logger.js";
import { isValidRegex } from "../utils/value-transforms.js";

const MODULE = "python-emitter";

/**
 * @typedef {Object} PipelineAST
 * @property {string}   name
 * @property {string}   targetOrigin
 * @property {object[]} steps
 */

/**
 * Emit a Python 3.11 script from a pipeline AST.
 * @param {PipelineAST} pipeline
 * @returns {string} Python source code
 */
export function emitPython(pipeline) {
  logger.info(MODULE, "emit-start", {
    name: pipeline.name,
    steps: pipeline.steps?.length,
  });

  const lines = [
    "#!/usr/bin/env python3",
    "# Generated by FlowScrape v3 — https://flowscrape.dev",
    `# Pipeline: ${_escStr(pipeline.name ?? "Untitled")}`,
    `# Generated: ${new Date().toISOString()}`,
    "",
    "import asyncio, os, re, json, csv, time, random",
    "from playwright.async_api import async_playwright",
    "import requests",
    "",
    "",
    "def fs_env(s):",
    '    """Resolve credential markers left by FlowScrape against the environment.',
    "",
    "    Credentials are not written into this script. Each one appears as",
    "    __FS_ENV__NAME__ and is read from the environment variable NAME when the",
    "    script runs; a name that is not set resolves to an empty string.",
    '    """',
    "    if not isinstance(s, str):",
    "        return s",
    '    return re.sub(r"__FS_ENV__([A-Z0-9_]+)__", lambda m: os.environ.get(m.group(1), ""), s)',
    "",
    "",
    "# ── Value transforms ─────────────────────────────────────────",
    "# Mirrors utils/value-transforms.js. The pipeline cleans values as it",
    "# extracts them; a script that skipped this would run, produce a file, and",
    "# fill the number columns with currency symbols.",
    "from urllib.parse import urljoin",
    "",
    "",
    "def fs_number(t):",
    '    m = re.search(r"-?\\d[\\d.,\\s]*\\d|-?\\d", str(t or ""))',
    "    if not m:",
    "        return None",
    '    b = re.sub(r"\\s", "", m.group(0))',
    '    c, d = b.rfind(","), b.rfind(".")',
    "    if c > -1 and d > -1:",
    '        dec, th = (",", ".") if c > d else (".", ",")',
    '        b = b.replace(th, "").replace(dec, ".")',
    "    elif c > -1:",
    '        after, single = len(b) - c - 1, b.find(",") == c',
    '        b = b.replace(",", ".") if single and 0 < after <= 2 else b.replace(",", "")',
    "    elif d > -1:",
    '        after, single = len(b) - d - 1, b.find(".") == d',
    "        if not (single and 0 < after <= 2):",
    '            b = b.replace(".", "")',
    "    try:",
    "        n = float(b)",
    "    except ValueError:",
    "        return None",
    "    return int(n) if n.is_integer() else n",
    "",
    "",
    "def fs_url(v, base):",
    '    return urljoin(base, str(v or "").strip()) if v else v',
    "",
    "",
    "def fs_regex(v, p):",
    '    m = re.search(p, str(v or ""))',
    "    if not m:",
    "        return None",
    "    return m.group(1) if m.groups() else m.group(0)",
    "",
    "",
    "def fs_trim(v):",
    '    return re.sub(r"\\s+", " ", str(v or "")).strip()',
    "",
    "",
    '# What an IF_ELSE branch reads before it decides. None means "no such',
    '# element", which every condition treats as not-matching rather than as an',
    "# empty string — the two are different, and conflating them puts every",
    "# missing row into the wrong branch.",
    "async def fs_text(loc):",
    "    return fs_trim(await loc.first.inner_text()) if await loc.count() > 0 else None",
    "",
    "",
    "async def fs_attr(loc, a):",
    "    return await loc.first.get_attribute(a) if await loc.count() > 0 else None",
    "",
    "# ── Config ────────────────────────────────────────────────────",
    `TARGET_ORIGIN = "${pipeline.targetOrigin ?? ""}"`,
    `MIN_DELAY_MS  = 800   # Floor enforced by FlowScrape ethics engine`,
    "",
    "# ── Proxy (set via environment variables) ────────────────────",
    "PROXY = {",
    '    "server":   os.environ.get("FS_PROXY_HOST", ""),',
    '    "username": os.environ.get("FS_PROXY_USER", ""),',
    '    "password": os.environ.get("FS_PROXY_PASS", ""),',
    '} if os.environ.get("FS_PROXY_HOST") else None',
    "",
    "",
    "async def run_pipeline():",
    "    async with async_playwright() as pw:",
    "        browser = await pw.chromium.launch(proxy=PROXY)",
    "        context = await browser.new_context()",
    "        page    = await context.new_page()",
    "",
    "        try:",
  ];

  for (const step of pipeline.steps ?? []) {
    const stepLines = _emitStep(step);
    lines.push(...stepLines.map((l) => "            " + l));
  }

  lines.push(
    "        finally:",
    "            await browser.close()",
    "",
    "",
    'if __name__ == "__main__":',
    "    asyncio.run(run_pipeline())",
    "",
  );

  const out = lines.join("\n");
  logger.info(MODULE, "emit-complete", { chars: out.length });
  return out;
}

/**
 * Emit step-specific Python code.
 * @param {object} step
 * @returns {string[]}
 */
/**
 * One IF_ELSE condition as a Python expression over `_loc`.
 *
 * Mirrors utils/conditions.js. Held to it by a test that emits every condition
 * in the registry and fails on any that comes back stubbed.
 *
 * @returns {string|null} null when the condition cannot be expressed
 */
function _conditionPy(condition, config) {
  const value = _escStr(String(config.value ?? ""));
  const attr = _escStr(String(config.attr ?? ""));
  const num = Number(String(config.value ?? "").trim());
  const numeric = (op) =>
    Number.isFinite(num)
      ? `(lambda n: n is not None and n ${op} ${num})(fs_number(await fs_text(_loc)))`
      : null;

  switch (condition) {
    case "exists":
      return `await _loc.count() > 0`;
    case "not-exists":
      return `await _loc.count() == 0`;
    case "is-empty":
      return `(lambda t: t is None or t == "")(await fs_text(_loc))`;
    case "not-empty":
      return `(lambda t: t is not None and t != "")(await fs_text(_loc))`;
    case "text-equals":
      return `await fs_text(_loc) == fs_trim("${value}")`;
    case "text-contains":
      return `(lambda t: t is not None and fs_trim("${value}") in t)(await fs_text(_loc))`;
    case "text-matches": {
      const raw = String(config.value ?? "");
      // A raw literal cannot end in a backslash, and such a pattern is not
      // valid anyway — refuse rather than trim it into something else.
      if (!isValidRegex(raw) || /\\$/.test(raw)) return null;
      return `(lambda t: t is not None and re.search(r"${raw.replace(/"/g, '\\"')}", t) is not None)(await fs_text(_loc))`;
    }
    case "attr-equals":
      return `(lambda a: a is not None and a.strip() == "${value}".strip())(await fs_attr(_loc, "${attr}"))`;
    case "attr-contains":
      return `(lambda a: a is not None and "${value}" in a)(await fs_attr(_loc, "${attr}"))`;
    case "attr-exists":
      return `await fs_attr(_loc, "${attr}") is not None`;
    case "number-equals":
      return numeric("==");
    case "number-gt":
      return numeric(">");
    case "number-lt":
      return numeric("<");
    default:
      return null;
  }
}

function _emitStep(step) {
  const { type, config = {} } = step;
  switch (type) {
    case "WEBSITE":
    case "NAVIGATE":
      return [
        `# NAVIGATE: ${config.url ?? ""}`,
        `await page.goto("${_escStr(config.url ?? "")}", wait_until="load")`,
        `await page.wait_for_load_state("networkidle")`,
        "",
      ];
    case "API":
      return _emitApi(config);
    case "CLICK":
      return [
        `# CLICK: ${config.selector ?? ""}`,
        `await page.click("${_escStr(config.selector ?? "")}")`,
        `await page.wait_for_load_state("networkidle")`,
        "",
      ];
    case "WAIT": {
      const timeout = Number(config.timeout) || 15000;
      if (config.mode === "selector-visible") {
        return [
          `await page.wait_for_selector("${_escStr(config.selector ?? "")}", state="visible", timeout=${timeout})`,
          "",
        ];
      }
      if (config.mode === "selector-gone") {
        return [
          `await page.wait_for_selector("${_escStr(config.selector ?? "")}", state="hidden", timeout=${timeout})`,
          "",
        ];
      }
      if (config.mode === "DOM-stable") {
        // Playwright has no "the DOM stopped changing"; network idle is the
        // closest equivalent, and what the mode is used for in practice.
        return [
          `await page.wait_for_load_state("networkidle", timeout=${timeout})`,
          "",
        ];
      }
      return [`await asyncio.sleep(${(config.ms ?? 1000) / 1000})`, ""];
    }
    case "EXTRACT":
      return _emitExtract(config);
    case "FORM_FILL":
      return _emitFormFill(config);
    case "EXPORT":
      return _emitExport(config);
    case "SCROLL": {
      // config.amount is what the UI writes; `value` was read here, so every
      // exported scroll used the hardcoded default of 300px.
      const amount = config.amount ?? config.value ?? 300;
      if (config.mode === "selector" && config.selector) {
        return [
          `await page.locator("${_escStr(config.selector)}").scroll_into_view_if_needed()`,
          "",
        ];
      }
      if (config.mode === "percent") {
        return [
          `await page.evaluate("window.scrollTo(0, document.documentElement.scrollHeight * ${Number(amount) / 100})")`,
          `await asyncio.sleep(0.5)`,
          "",
        ];
      }
      if (config.mode === "infinite" || config.mode === "bottom") {
        const maxScrolls = Number(config.maxScrolls) || 50;
        const settle = (Number(config.settleMs) || 1200) / 1000;
        return [
          `# Scroll until the page stops growing, or ${maxScrolls} scrolls.`,
          `_last_height = 0`,
          `for _ in range(${maxScrolls}):`,
          `    await page.evaluate("window.scrollTo(0, document.documentElement.scrollHeight)")`,
          `    await asyncio.sleep(${settle})`,
          `    _h = await page.evaluate("document.documentElement.scrollHeight")`,
          `    if _h == _last_height:`,
          `        break`,
          `    _last_height = _h`,
          "",
        ];
      }
      return [
        `await page.evaluate("window.scrollBy(0, ${amount})")`,
        `await asyncio.sleep(0.5)`,
        "",
      ];
    }
    case "LOOP": {
      const lines = [
        `# LOOP: ${config.type || "count"} (max: ${config.max ?? 10})`,
      ];
      if (config.type === "elements" && config.selector) {
        lines.push(
          `elements = await page.locator("${_escStr(config.selector)}").all()`,
        );
        lines.push(`for i, el in enumerate(elements[:${config.max ?? 10}]):`);
      } else {
        lines.push(`for i in range(${config.max ?? 10}):`);
      }
      if (config.type === "paginate" && config.selector) {
        // The emitted loop ignored paginate mode entirely: it ran the body N
        // times without ever clicking Next, so the script scraped page one N
        // times over.
        lines.push(
          `    if i > 0:`,
          `        _next = page.locator("${_escStr(config.selector)}").first`,
          `        if await _next.count() == 0 or not await _next.is_enabled():`,
          `            print(f"Pagination: stopped after {i} page(s).")`,
          `            break`,
          `        await _next.click()`,
          `        await page.wait_for_load_state("networkidle")`,
        );
      }
      for (const child of step.children ?? []) {
        lines.push(..._emitStep(child).map((l) => "    " + l));
      }
      if (!step.children || step.children.length === 0) lines.push("    pass");
      lines.push("");
      return lines;
    }
    case "IF_ELSE": {
      const condition = config.condition || "exists";
      const lines = [
        `# IF_ELSE: ${condition} - ${_escStr(config.selector ?? "")}`,
      ];
      const test = _conditionPy(condition, config);
      if (test === null) {
        // Emitted as a refusal rather than as `if True:`, which is what this
        // used to do for every condition but `exists`: the script ran, produced
        // a file, and had silently ignored its own branching.
        lines.push(
          `# UNSUPPORTED: condition "${condition}" cannot be expressed here.`,
          `raise ValueError("FlowScrape: IF_ELSE condition '${condition}' is not exportable")`,
          "",
        );
        return lines;
      }
      lines.push(
        `_loc = page.locator("${_escStr(config.selector ?? "")}")`,
        `if ${test}:`,
      );
      for (const child of step.ifBranch ?? []) {
        lines.push(..._emitStep(child).map((l) => "    " + l));
      }
      if (!step.ifBranch || step.ifBranch.length === 0) lines.push("    pass");
      lines.push(`else:`);
      for (const child of step.elseBranch ?? []) {
        lines.push(..._emitStep(child).map((l) => "    " + l));
      }
      if (!step.elseBranch || step.elseBranch.length === 0)
        lines.push("    pass");
      lines.push("");
      return lines;
    }
    case "FILL":
    case "TYPE":
      return _emitFill(config);

    case "HOVER":
      return [
        `# HOVER: ${config.selector ?? ""}`,
        `await page.hover("${_escStr(config.selector ?? "")}")`,
        "",
      ];

    case "SELECT":
      return [
        `# SELECT: ${config.selector ?? ""}`,
        `await page.select_option("${_escStr(config.selector ?? "")}", "${_escStr(config.value ?? "")}")`,
        "",
      ];

    case "KEYBOARD":
      return [
        `# KEYBOARD: ${config.key ?? "Enter"}`,
        `await page.keyboard.press("${_escStr(_playwrightKey(config.key))}")`,
        "",
      ];

    case "SCREENSHOT":
      return [
        "# SCREENSHOT",
        `await page.screenshot(path=f"screenshot_{int(time.time() * 1000)}.png")`,
        "",
      ];

    case "PAGE_DATA": {
      // The same subset the Node emitter carries, for the same reason: JSON-LD
      // and meta tags travel cleanly; a second microdata reader here would
      // drift from content/page-data.js. The script says so when it finds
      // nothing, rather than differing in silence.
      const wantType = String(config.type ?? "").toLowerCase();
      const flat = config.flatten !== false;
      const js = [
        "() => {",
        "  const abs = v => { try { return new URL(String(v ?? '').trim(), location.href).href; } catch { return v; } };",
        "  const records = [];",
        "  const walk = (d, depth = 0) => {",
        "    if (!d || depth > 6) return;",
        "    if (Array.isArray(d)) return d.forEach(x => walk(x, depth + 1));",
        "    if (typeof d !== 'object') return;",
        "    if (Array.isArray(d['@graph'])) {",
        "      d['@graph'].forEach(x => walk(x, depth + 1));",
        "      if (Object.keys(d).filter(k => k !== '@graph' && k !== '@context').length === 0) return;",
        "    }",
        "    records.push(d);",
        "  };",
        // Double quotes inside the JS, on purpose: the snippet is embedded in a
        // Python \"\"\"…\"\"\" literal, where a backslash-escaped single quote is
        // resolved by Python before the browser ever sees it — leaving the JS
        // string unterminated. A double quote needs no escape in either.
        "  for (const el of document.querySelectorAll('script[type=\"application/ld+json\"]')) {",
        "    try { walk(JSON.parse(el.textContent || '')); } catch {}",
        "  }",
        "  const meta = {};",
        "  for (const el of document.querySelectorAll('meta[content]')) {",
        "    const k = el.getAttribute('property') || el.getAttribute('name');",
        "    if (!k) continue;",
        "    if (!/^(og|twitter|product|article|book|music|video|profile):/.test(k) &&",
        "        !['description','keywords','author','robots'].includes(k)) continue;",
        "    const v = el.getAttribute('content');",
        "    meta[k] = /(?:^|:)(?:url|image|video|audio|player)$/.test(k) ? abs(v) : String(v ?? '').replace(/\\s+/g, ' ').trim();",
        "  }",
        "  return { records, meta, url: location.href, title: document.title };",
        "}",
      ].join(" ");

      const lines = [
        "# PAGE_DATA — the page's own structured data, no selectors",
        `page_data = await page.evaluate("""${js}""")`,
      ];
      if (wantType) {
        lines.push(
          `page_data["records"] = [r for r in page_data["records"]`,
          `    if ${JSON.stringify(wantType)} in [str(t).lower() for t in (r.get("@type") if isinstance(r.get("@type"), list) else [r.get("@type")])]]`,
        );
      }
      lines.push(
        'if not page_data["records"]:',
        '    print("PAGE_DATA: no JSON-LD found. The extension would also try microdata here;")',
        '    print("           this script does not carry that reader, so the result may differ.")',
      );
      if (flat) {
        lines.push(
          "",
          "def _fs_flat(v, p='', out=None, depth=0):",
          "    out = {} if out is None else out",
          "    if v is None:",
          "        return out",
          "    if isinstance(v, list):",
          "        if all(not isinstance(x, (dict, list)) for x in v):",
          "            out[p or 'value'] = ', '.join(str(x) for x in v)",
          "        else:",
          "            for i, x in enumerate(v):",
          "                _fs_flat(x, f'{p}.{i}' if p else str(i), out, depth + 1)",
          "        return out",
          "    if isinstance(v, dict):",
          "        if depth >= 6:",
          "            return out",
          "        for k, val in v.items():",
          "            _fs_flat(val, f'{p}.{k}' if p else k, out, depth + 1)",
          "        return out",
          "    out[p or 'value'] = v",
          "    return out",
          "",
          'page_data["records"] = [_fs_flat(r) for r in page_data["records"]]',
        );
      }
      lines.push(
        'for record in page_data["records"]:',
        "    print(json.dumps(record))",
        "",
      );
      return lines;
    }

    case "PAGINATE": {
      // A bare click was what this emitted, so past the last page the script
      // carried on believing it had turned one. `break` is not emitted here:
      // a top-level PAGINATE has no loop to leave. A paginating LOOP emits
      // its own.
      const sel = _escStr(config.selector ?? "");
      return [
        `# PAGINATE: ${config.selector ?? ""}`,
        `_next = page.locator("${sel}").first`,
        `if await _next.count() > 0 and await _next.is_enabled():`,
        `    await _next.click()`,
        `    await page.wait_for_load_state("networkidle")`,
        `else:`,
        `    print("Pagination: no further pages.")`,
        "",
      ];
    }

    case "DRAG_DROP":
      return [
        `# DRAG_DROP: ${config.source ?? ""} -> ${config.target ?? ""}`,
        `await page.drag_and_drop("${_escStr(config.source ?? "")}", "${_escStr(config.target ?? "")}")`,
        "",
      ];

    default:
      // Not silently dropped: emitUnsupported collects these and the caller
      // reports them, so an exported script cannot quietly do less than the
      // pipeline it came from.
      return [
        `# UNSUPPORTED: "${type}" has no equivalent in a standalone script.`,
        `raise NotImplementedError("FlowScrape step ${type} is not exportable")`,
        "",
      ];
  }
}

/** Playwright key names differ slightly from the panel's combo strings. */
function _playwrightKey(key) {
  return String(key ?? "Enter")
    .split("+")
    .map((part) => (part === "Ctrl" ? "Control" : part))
    .join("+");
}

function _emitFill(config) {
  const lines = ["# FILL"];
  const fields =
    config.mode === "multi" &&
    Array.isArray(config.fields) &&
    config.fields.length
      ? config.fields
      : [{ selector: config.selector, value: config.text }];

  for (const field of fields) {
    if (!field?.selector) continue;
    lines.push(
      `await page.fill("${_escStr(field.selector)}", fs_env("${_escStr(field.value ?? "")}"))`,
    );
  }
  if (config.submitSelector) {
    lines.push(`await page.click("${_escStr(config.submitSelector)}")`);
    lines.push(`await page.wait_for_load_state("networkidle")`);
  }
  lines.push("");
  return lines;
}

/**
 * Wrap a read in the transforms the field carries, innermost first.
 * @returns {string|null} null when a transform cannot be emitted faithfully
 */
function _transformPy(expr, field) {
  let out = expr;
  for (const name of field.transform ?? []) {
    if (name === "number") out = `fs_number(${out})`;
    else if (name === "trim") out = `fs_trim(${out})`;
    else if (name === "url") out = `fs_url(${out}, page.url)`;
    else if (name === "lower") out = `str(${out} or "").lower()`;
    else if (name === "upper") out = `str(${out} or "").upper()`;
    else if (name === "regex") {
      const raw = String(field.regexPattern ?? "");
      // A raw literal cannot end in a backslash, and a lone trailing backslash
      // is not a valid pattern anyway — so refuse rather than trim it, which
      // would give a script that extracts something else without saying so.
      if (!isValidRegex(raw) || /\\$/.test(raw)) return null;
      // r"" means a backslash stands for itself, so _escStr's doubling would
      // turn `\S` into a literal backslash followed by S. Only the quote
      // needs handling.
      out = `fs_regex(${out}, r"${raw.replace(/"/g, '\\"')}")`;
    }
  }
  return out;
}

function _emitExtract(config) {
  const lines = ["# EXTRACT"];
  const fields = config.fields ?? config.schema ?? [];
  if (fields.length === 0) return ["# EXTRACT: no fields defined", ""];
  lines.push("extracted = {}");
  for (const field of fields) {
    const { name, selector, attribute, countSelector } = field;
    // "count" reads a value the page shows as repetition — four filled stars
    // is the rating 4. Playwright's locator count is the same question the
    // in-page reader asks with querySelectorAll, so the script and the run
    // return the same number rather than the script quietly omitting a column.
    const read =
      field.type === "count"
        ? `str(await page.locator("${_escStr(selector)}").first.locator("${_escStr(countSelector ?? "")}").count())`
        : attribute
          ? `await page.get_attribute("${_escStr(selector)}", "${attribute}")`
          : `await page.inner_text("${_escStr(selector)}")`;
    if (field.type === "count" && !countSelector) {
      lines.push(
        `# INVALID: field "${name}" is set to Count but names nothing to count.`,
        `raise ValueError("FlowScrape field '${name}': Count needs a selector")`,
      );
      continue;
    }
    const expr = _transformPy(read, field);
    if (expr === null) {
      lines.push(
        `# INVALID: field "${name}" has a pattern this script cannot carry.`,
        `raise ValueError("FlowScrape field '${name}': invalid regex pattern")`,
      );
      continue;
    }
    lines.push(`extracted["${name}"] = ${expr}`);
  }
  lines.push("print(json.dumps(extracted))", "");
  return lines;
}

function _emitFormFill(config) {
  const lines = [
    "# FORM_FILL — read data from file",
    'DATA_FILE = os.environ.get("FS_DATA_FILE", "data.csv")',
    'with open(DATA_FILE, newline="", encoding="utf-8") as f:',
    "    reader = csv.DictReader(f)",
    "    for row in reader:",
  ];
  for (const mapping of config.fieldMappings ?? []) {
    const sel = _escStr(mapping.selector ?? "");
    const col = _escStr(mapping.column ?? "");
    const type = mapping.inputType ?? "text";
    if (type === "select") {
      lines.push(
        `        await page.select_option("${sel}", row.get("${col}", ""))`,
      );
    } else if (type === "checkbox") {
      lines.push(
        `        if row.get("${col}", "").lower() in ("yes","true","1","y"):`,
      );
      lines.push(`            await page.check("${sel}")`);
    } else {
      lines.push(`        await page.fill("${sel}", row.get("${col}", ""))`);
    }
  }
  if (config.submitSelector) {
    lines.push(`        await page.click("${_escStr(config.submitSelector)}")`);
  }
  const delay = (config.interRowDelay?.min ?? 1200) / 1000;
  lines.push(`        await asyncio.sleep(${delay} + random.random())`);
  lines.push("");
  return lines;
}

function _emitExport(config) {
  return [
    `# EXPORT → ${config.format ?? "csv"}`,
    "# (Results were collected into list during FORM_FILL / EXTRACT steps)",
    "# Write to file here",
    "",
  ];
}

function _emitApi(config) {
  const url = _escStr(config.url ?? "");
  const method = String(config.method ?? "GET").toUpperCase();
  const headers = _escStr(config.headers ?? '{"Accept":"application/json"}');
  const body = _escStr(config.body ?? "");
  const timeoutSec = (Number(config.timeoutMs ?? 15000) / 1000).toFixed(2);
  const failOnHttp = config.failOnHttpError !== false;

  const lines = [
    "# API",
    `api_headers = {}`,
    `try:`,
    `    api_headers = json.loads(fs_env("""${headers}""")) if """${headers}""".strip() else {}`,
    `except Exception:`,
    `    api_headers = {}`,
    `api_resp = requests.request(`,
    `    method="${method}",`,
    `    url="${url}",`,
    `    headers=api_headers,`,
    `    data=fs_env("""${body}""") if """${body}""" else None,`,
    `    timeout=${timeoutSec},`,
    `)`,
  ];

  if (failOnHttp) lines.push("api_resp.raise_for_status()");

  lines.push(
    "try:",
    "    api_body = api_resp.json()",
    "except Exception:",
    "    api_body = api_resp.text",
    'api_result = {"ok": api_resp.ok, "status": api_resp.status_code, "body": api_body}',
    'print("API_RESULT", json.dumps(api_result))',
    "",
  );
  return lines;
}

function _escStr(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// === END python-emitter.js ===
