// === python-emitter.js ===
/**
 * @module python-emitter
 * @description Converts a pipeline JSON AST to Python 3.11 script
 *   using playwright (browser automation) + requests (HTTP).
 *   Secrets are always redacted in output — replaced with environment variable references.
 *
 *   Design decision: We emit Python rather than Playwright-specific code because
 *   Python is the most common scripting language for automation. The output is
 *   self-contained: user runs `pip install playwright requests && playwright install`.
 *
 * @dependencies logger
 */

import { logger } from '../utils/logger.js';

const MODULE = 'python-emitter';

/**
 * @typedef {Object} PipelineAST
 * @property {string}   name
 * @property {string}   targetOrigin
 * @property {object[]} steps
 */

/**
 * Emit a Python 3.11 script from a pipeline AST.
 * @param {PipelineAST} pipeline
 * @returns {string} Python source code
 */
export function emitPython(pipeline) {
  logger.info(MODULE, 'emit-start', { name: pipeline.name, steps: pipeline.steps?.length });

  const lines = [
    '#!/usr/bin/env python3',
    '# Generated by FlowScrape v3 — https://flowscrape.dev',
    `# Pipeline: ${_escStr(pipeline.name ?? 'Untitled')}`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    'import asyncio, os, json, csv, time, random',
    'from playwright.async_api import async_playwright',
    'import requests',
    '',
    '# ── Config ────────────────────────────────────────────────────',
    `TARGET_ORIGIN = "${pipeline.targetOrigin ?? ''}"`,
    `MIN_DELAY_MS  = 800   # Floor enforced by FlowScrape ethics engine`,
    '',
    '# ── Proxy (set via environment variables) ────────────────────',
    'PROXY = {',
    '    "server":   os.environ.get("FS_PROXY_HOST", ""),',
    '    "username": os.environ.get("FS_PROXY_USER", ""),',
    '    "password": os.environ.get("FS_PROXY_PASS", ""),',
    '} if os.environ.get("FS_PROXY_HOST") else None',
    '',
    '',
    'async def run_pipeline():',
    '    async with async_playwright() as pw:',
    '        browser = await pw.chromium.launch(proxy=PROXY)',
    '        context = await browser.new_context()',
    '        page    = await context.new_page()',
    '',
    '        try:',
  ];

  for (const step of (pipeline.steps ?? [])) {
    const stepLines = _emitStep(step);
    lines.push(...stepLines.map(l => '            ' + l));
  }

  lines.push(
    '        finally:',
    '            await browser.close()',
    '',
    '',
    'if __name__ == "__main__":',
    '    asyncio.run(run_pipeline())',
    ''
  );

  const out = lines.join('\n');
  logger.info(MODULE, 'emit-complete', { chars: out.length });
  return out;
}

/**
 * Emit step-specific Python code.
 * @param {object} step
 * @returns {string[]}
 */
function _emitStep(step) {
  const { type, config = {} } = step;
  switch (type) {
    case 'NAVIGATE':
      return [
        `# NAVIGATE: ${config.url ?? ''}`,
        `await page.goto("${_escStr(config.url ?? '')}", wait_until="load")`,
        `await page.wait_for_load_state("networkidle")`,
        '',
      ];
    case 'CLICK':
      return [
        `# CLICK: ${config.selector ?? ''}`,
        `await page.click("${_escStr(config.selector ?? '')}")`,
        `await page.wait_for_load_state("networkidle")`,
        '',
      ];
    case 'WAIT':
      if (config.mode === 'selector-visible') {
        return [`await page.wait_for_selector("${_escStr(config.selector ?? '')}")`, ''];
      }
      return [`await asyncio.sleep(${(config.ms ?? 1000) / 1000})`, ''];
    case 'EXTRACT':
      return _emitExtract(config);
    case 'FORM_FILL':
      return _emitFormFill(config);
    case 'EXPORT':
      return _emitExport(config);
    case 'SCROLL':
      return [
        `await page.evaluate("window.scrollBy(0, ${config.value ?? 300})")`,
        `await asyncio.sleep(0.5)`,
        '',
      ];
    default:
      return [`# TODO: implement step type "${type}"`, ''];
  }
}

function _emitExtract(config) {
  const lines = ['# EXTRACT'];
  const fields = config.fields ?? config.schema ?? [];
  if (fields.length === 0) return ['# EXTRACT: no fields defined', ''];
  lines.push('extracted = {}');
  for (const { name, selector, attribute } of fields) {
    if (attribute) {
      lines.push(`extracted["${name}"] = await page.get_attribute("${_escStr(selector)}", "${attribute}")`);
    } else {
      lines.push(`extracted["${name}"] = await page.inner_text("${_escStr(selector)}")`);
    }
  }
  lines.push('print(json.dumps(extracted))', '');
  return lines;
}

function _emitFormFill(config) {
  const lines = [
    '# FORM_FILL — read data from file',
    'DATA_FILE = os.environ.get("FS_DATA_FILE", "data.csv")',
    'with open(DATA_FILE, newline="", encoding="utf-8") as f:',
    '    reader = csv.DictReader(f)',
    '    for row in reader:',
  ];
  for (const mapping of (config.fieldMappings ?? [])) {
    const sel = _escStr(mapping.selector ?? '');
    const col = _escStr(mapping.column ?? '');
    const type = mapping.inputType ?? 'text';
    if (type === 'select') {
      lines.push(`        await page.select_option("${sel}", row.get("${col}", ""))`);
    } else if (type === 'checkbox') {
      lines.push(`        if row.get("${col}", "").lower() in ("yes","true","1","y"):`);
      lines.push(`            await page.check("${sel}")`);
    } else {
      lines.push(`        await page.fill("${sel}", row.get("${col}", ""))`);
    }
  }
  if (config.submitSelector) {
    lines.push(`        await page.click("${_escStr(config.submitSelector)}")`);
  }
  const delay = (config.interRowDelay?.min ?? 1200) / 1000;
  lines.push(`        await asyncio.sleep(${delay} + random.random())`);
  lines.push('');
  return lines;
}

function _emitExport(config) {
  return [
    `# EXPORT → ${config.format ?? 'csv'}`,
    '# (Results were collected into list during FORM_FILL / EXTRACT steps)',
    '# Write to file here',
    '',
  ];
}

function _escStr(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// === END python-emitter.js ===
