// === strings.js ===
/**
 * @module strings
 * @description All UI strings for FlowScrape v3. i18n-ready key-value map.
 *   Import this module everywhere you need user-facing text.
 *   All keys are UPPER_SNAKE_CASE. Never hardcode UI strings elsewhere.
 * @dependencies none
 */

'use strict';

export const S = Object.freeze({
  // General
  APP_NAME:                    'FlowScrape v3',
  VERSION:                     '3.0.0',
  LOADING:                     'Loading…',
  SAVING:                      'Saving…',
  SAVED:                       'Saved',
  ERROR:                       'Error',
  WARNING:                     'Warning',
  SUCCESS:                     'Success',
  CONFIRM:                     'Confirm',
  CANCEL:                      'Cancel',
  OK:                          'OK',
  CLOSE:                       'Close',
  DELETE:                      'Delete',
  EXPORT:                      'Export',
  IMPORT:                      'Import',
  ADD:                         'Add',
  REMOVE:                      'Remove',
  EDIT:                        'Edit',
  SAVE:                        'Save',
  TEST:                        'Test',
  RUN:                         'Run',
  PAUSE:                       'Pause',
  STOP:                        'Stop',
  RESUME:                      'Resume',
  CLEAR:                       'Clear All',
  PREVIEW:                     'Preview',
  UNKNOWN:                     'Unknown',

  // Proxy Panel
  PROXY_TITLE:                 'Proxy Pool Manager',
  PROXY_PASTE:                 'Paste Proxies',
  PROXY_UPLOAD_CSV:            'Upload CSV',
  PROXY_API_FEED:              'API Feed URL',
  PROXY_ROTATION_LABEL:        'Rotation Mode',
  PROXY_MODE_RR:               'Round-Robin',
  PROXY_MODE_RANDOM:           'Random',
  PROXY_MODE_STICKY:           'Sticky',
  PROXY_MODE_GEO:              'Geo-Target',
  PROXY_TEST_ALL:              'Test All',
  PROXY_COL_HOST:              'Host',
  PROXY_COL_PORT:              'Port',
  PROXY_COL_LATENCY:           'Latency',
  PROXY_COL_COUNTRY:           'Country',
  PROXY_COL_STATUS:            'Status',
  PROXY_STATUS_ALIVE:          'Alive',
  PROXY_STATUS_DEAD:           'Dead',
  PROXY_AUTO_REMOVE:           'Auto-Remove',
  PROXY_KEEP_RETRY:            'Keep + Retry (max 3×)',
  PROXY_SAVE_POOL:             'Save Pool',
  PROXY_EXPORT_HOSTS:          'Export (hosts only)',
  PROXY_LAST_TESTED:           'Last tested',
  PROXY_ALIVE_COUNT:           'alive',
  PROXY_PARSE_ERROR:           'Could not parse proxy entry',
  PROXY_DUPE_SKIPPED:          'Duplicate proxy skipped',
  PROXY_HEALTH_TIMEOUT:        'Proxy health check timed out',
  PROXY_ALL_DEAD:              'All proxies are dead — pipeline paused',

  // API Key Panel
  APIKEY_TITLE:                'API Key Manager',
  APIKEY_ADD:                  'Add Key',
  APIKEY_AUTO_DISCOVER:        'Auto-Discover',
  APIKEY_SECTION_CAPTCHA:      'Captcha Solvers',
  APIKEY_SECTION_ENRICHMENT:   'Data Enrichment',
  APIKEY_SECTION_NOTIFY:       'Notifications',
  APIKEY_VALID:                'Valid',
  APIKEY_INVALID:              'Invalid',
  APIKEY_UNKNOWN:              'Not validated',
  APIKEY_SESSION_NOTICE:       'All key values stored in session memory only (cleared on close)',
  APIKEY_EXPORT_NAMES:         'Export key names + status only',
  APIKEY_BALANCE:              'Balance',
  APIKEY_SOLVED_TODAY:         'Solved today',
  APIKEY_RATE:                 'Rate',
  APIKEY_VALIDATION_FAIL:      'Key validation failed',
  APIKEY_NETWORK_ERROR:        'Network error during validation',

  // Form Fill Panel
  FORM_FILL_TITLE:             'Form Fill — Step Configuration',
  FORM_DATA_SOURCE:            'Data Source',
  FORM_UPLOAD_FILE:            'Upload CSV / JSON / XLSX',
  FORM_USE_PIPELINE:           'Use Pipeline Dataset',
  FORM_LOADED:                 'loaded',
  FORM_ROWS:                   'rows',
  FORM_COLUMNS:                'columns',
  FORM_FIELD_MAPPING:          'Field Mapping',
  FORM_AUTO_MAP:               'Auto-Map',
  FORM_COL_DATASET:            'Dataset Column',
  FORM_COL_SELECTOR:           'Selector (click 🖱 to pick)',
  FORM_COL_TYPE:               'Type',
  FORM_ADD_ROW:                '+ add row',
  FORM_AUTOMAP_CONFIDENCE:     'Auto-map confidence',
  FORM_SUBMIT_SELECTOR:        'Submit selector',
  FORM_WAIT_AFTER:             'After submit',
  FORM_SUCCESS_SELECTOR:       'Success selector',
  FORM_ERROR_SELECTOR:         'Error selector',
  FORM_ON_ERROR:               'On error',
  FORM_ON_ERROR_LOG:           'Log & Continue',
  FORM_ON_ERROR_STOP:          'Stop Run',
  FORM_ON_ERROR_RETRY:         'Retry',
  FORM_TIMING:                 'Timing',
  FORM_BETWEEN_ROWS_MIN:       'Min',
  FORM_BETWEEN_ROWS_MAX:       'Max',
  FORM_JITTER:                 'Jitter',
  FORM_FLOOR_NOTICE:           '(Floor: 800ms enforced regardless of setting)',
  FORM_CAPTCHA_SECTION:        'Captcha',
  FORM_CAPTCHA_DISABLED:       'Disabled by default.',
  FORM_CAPTCHA_AUTHORIZE:      'I have authorization to automate this site → Enable solving',
  FORM_TEST_ROW1:              'Test with Row 1',
  FORM_RUN_ALL:                'Run All',
  FORM_ROWS_LABEL:             'Rows',
  FORM_PREVIEW_OUTPUT:         'Preview Output',
  FORM_PII_WARNING:            'PII detected in data source. Proceed with caution.',
  FORM_PII_CONFIRM:            'I understand — proceed',
  FORM_CAP_WARNING:            'Row count exceeds 500. Confirm to proceed up to 5000.',
  FORM_CAP_CONFIRM:            'I understand, run up to 5000 rows',
  FORM_ETHICS_NO_PASS:         'Cannot fill password fields — ethics block',
  FORM_ETHICS_HIDDEN:          'Cannot fill hidden fields — ethics block',
  FORM_ETHICS_DOMAIN:          'Submit target domain does not match pipeline origin — ethics block',
  FORM_ETHICS_DELAY_FLOOR:     'Inter-row delay cannot be below 800ms — ethics block',

  // Pipeline Builder
  PIPELINE_TITLE:              'FlowScrape v3',
  PIPELINE_AUTO_DETECT:        'Auto-Detect',
  PIPELINE_ADD_STEP:           'Add Step',
  PIPELINE_EXPORT_SCRIPT:      'Export Script',
  PIPELINE_FORM_FILL:          'Form Fill',
  PIPELINE_API_PROBE:          'API Probe',
  PIPELINE_RUN_DASHBOARD:      'Run Dashboard',
  PIPELINE_SETTINGS:           'Settings',
  PIPELINE_PROXY_HEADER:       'Proxy',
  PIPELINE_KEY_HEADER:         'Keys',
  PIPELINE_INSERT_STEP:        '+ insert step',
  PIPELINE_STEP_NAVIGATE:      'NAVIGATE',
  PIPELINE_STEP_FORM_FILL:     'FORM_FILL',
  PIPELINE_STEP_EXTRACT:       'EXTRACT',
  PIPELINE_STEP_EXPORT:        'EXPORT',
  PIPELINE_STEP_CONDITIONAL:   'CONDITIONAL',
  PIPELINE_STEP_WAIT:          'WAIT',
  PIPELINE_STEP_CLICK:         'CLICK',
  PIPELINE_STEP_SCROLL:        'SCROLL',
  PIPELINE_NO_STEPS:           'No steps yet. Click [+ Add Step] to begin.',

  // Run Dashboard
  DASH_ROWS:                   'Rows',
  DASH_ERRORS:                 'Errors',
  DASH_IP_ROTATIONS:           'IP rotations',
  DASH_SUBMITTED:              'submitted',
  DASH_CAPTCHAS:               'Captchas solved',
  DASH_CHECKPOINT:             'Checkpoint saved',
  DASH_RESUME_AVAIL:           'Resume available',
  DASH_PAUSE:                  'Pause',
  DASH_STOP_RUN:               'Stop',
  DASH_PREVIEW_DATA:           'Preview Data',
  DASH_EXPORT_NOW:             'Export Now',
  DASH_COMPLETE:               'Run complete',
  DASH_PAUSED:                 'Paused',
  DASH_STOPPED:                'Stopped',
  DASH_RUNNING:                'Running',

  // Ethics
  ETHICS_ROBOTS_WARN:          'robots.txt disallows crawling this path. Proceed?',
  ETHICS_PII_WARN:             'PII patterns detected in input data.',
  ETHICS_HIGH_RATE_WARN:       'Estimated rate exceeds 100 req/hr. Proceed?',
  ETHICS_PROXY_GEO_WARN:       'Proxy geo-origin differs from declared region by > 5000km.',
  ETHICS_HIGH_CAPTCHA_WARN:    'Estimated > 50 captcha solves/hr.',
  ETHICS_DOMAIN_MISMATCH:      'Cross-origin form submission blocked.',
  ETHICS_PASSWORD_BLOCK:       'Filling password fields is not permitted.',
  ETHICS_HIDDEN_BLOCK:         'Filling hidden fields is not permitted.',
  ETHICS_CAP_EXCEEDED:         'Row submission cap exceeded.',
  ETHICS_DELAY_FLOOR:          'Inter-row delay below minimum (800ms) is not permitted.',

  // Errors
  ERR_PROXY_NONE_ALIVE:        'No alive proxies in pool.',
  ERR_PROXY_ROTATE_FAIL:       'Failed to rotate proxy.',
  ERR_KEY_DECRYPT:             'Failed to decrypt API key.',
  ERR_KEY_ENCRYPT:             'Failed to encrypt API key.',
  ERR_STORAGE_READ:            'Failed to read from storage.',
  ERR_STORAGE_WRITE:           'Failed to write to storage.',
  ERR_IDB_OPEN:                'Failed to open IndexedDB.',
  ERR_IDB_WRITE:               'Failed to write to IndexedDB.',
  ERR_IDB_READ:                'Failed to read from IndexedDB.',
  ERR_PARSE_CSV:               'CSV parse error.',
  ERR_PARSE_JSON:              'JSON parse error.',
  ERR_PARSE_XLSX:              'XLSX parse error.',
  ERR_SELECT_NOT_FOUND:        'Could not find select option.',
  ERR_SELECTOR_NO_MATCH:       'Selector matched no elements.',
  ERR_CAPTCHA_GATE:            'Captcha solving blocked by ethics gate.',
  ERR_MAX_RETRIES:             'Maximum retries exceeded.',
});

// === END strings.js ===
